# Generated by Django 4.0.2 on 2022-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
