# Generated by Django 4.0.2 on 2022-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_questao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='isCorreta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
