# Generated by Django 4.0.2 on 2022-08-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_perfil_id_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='contas/imagens/'),
        ),
    ]
