# Generated by Django 4.0.2 on 2022-08-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='contas/imagens'),
        ),
    ]
