# Generated by Django 4.0.2 on 2022-09-28 00:09

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='resumo',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 28, 0, 9, 56, 785693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topico',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
