# Generated by Django 4.0.2 on 2022-09-28 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_data_publicacao_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 9, 28, 0, 49, 37, 864000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 28, 0, 49, 37, 857384, tzinfo=utc)),
        ),
    ]
