# Generated by Django 4.0.2 on 2022-09-28 00:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_situacao_data_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacao',
            name='data',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 28, 0, 51, 5, 666928, tzinfo=utc)),
        ),
    ]
