# Generated by Django 4.0.2 on 2022-09-28 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_situacao_data_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 28, 1, 41, 46, 321330, tzinfo=utc)),
        ),
    ]
